name: Run Python Script on Windows

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 02:00 UTC (2 + 6 = 8 AM) every day
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python Codeforces.py
      
      - name: Run script
        run: python mail.py
      
